// databases.js
const databases = {
    karate: [
        { id: "GlazovL73", name: "Глазов Лев" },
        { id: "VlasiukM44", name: "Власюк Максим" },
        { id: "ShestilovskiiN68", name: "Шестиловский Никита" },
        { id: "VlaskinP51", name: "Власкин Пётр" },
        { id: "RudkoN86", name: "Рудько Назар" },
        { id: "GlushankovM39", name: "Глушанков Матвей" },
        { id: "KorpilevM40", name: "Корпылев Мирослав" },
        { id: "FilimonovaY85", name: "Филимонова Яна" },
        { id: "SharipovA57", name: "Шарипов Артем" },
        { id: "VyblyiL62", name: "Выблый Лев" },
        { id: "MagomedovA91", name: "Магомедов Али" },
        { id: "TurkinN35", name: "Туркин Николай" },
        { id: "TurkinK27", name: "Туркин Кирилл" },
        { id: "SharipovI19", name: "Шарипов Илья" },
        { id: "BalalaikinaM84", name: "Балалайкина Милана" },
        { id: "ErshovaI78", name: "Ершова Юлиана" },
        { id: "PreobrajenskiiK25", name: "Преображенский Константин" },
        { id: "VorobievV45", name: "Воробьев Владислав" },
        { id: "VoinovM33", name: "Войнов Михаил" }
    ],

    engineers: [
    { id: "ZhuravlevaE96", name: "Журавлева Ева" },
    { id: "KaisinaK55", name: "Кайсина Кира" },
    { id: "SolyakinA30", name: "Солякин Алексей" },
    { id: "DanilukV17", name: "Данилюк Виктория" },
    { id: "ImamovD64", name: "Имамов Динар" },
    { id: "BadalyanA83", name: "Бадалян Аврора" },
    { id: "DobrenkovI70", name: "Добренков Ивар" },
    { id: "ShcherbakovM41", name: "Щербаков Матвей" },
    { id: "MazzhukhinM76", name: "Мазжухин Матвей" },
    { id: "GalstyanL29", name: "Галстян Лев" },
    { id: "AlievaN77", name: "Алиева Николь" },
    { id: "KapitonovM17", name: "Капитонов Михаил" },
    { id: "OstapchukA15", name: "Остапчук Арсений" },
    { id: "Savenkov64", name: "Савенков Илья" },
    { id: "ZicinL25", name: "Цыцын Лука" },
    { id: "IvanushkinM09", name: "Иванушкин Марк" },
    { id: "ShilinM81", name: "Шилин Максим" },
    { id: "BaranovD88", name: "Баранов Даниил" },
    { id: "ChzhouS77", name: "Чжоу Шуянь" },
    { id: "Zhuii23", name: "У Жуйи" },
    { id: "SidorovF63", name: "Сидоров Фёдор" },
    { id: "RutskiyY33", name: "Руцкий Ян" },
    { id: "DjahayaS42", name: "Джахая Сандро" },
    { id: "StepanenkoM65", name: "Степаненко Мия" },
    { id: "ZhuravlevaA51", name: "Журавлева Аврора" },
    { id: "KazaryanA12", name: "Казарян Артемий" },
    { id: "KuznetsovA68", name: "Кузнецов Арсений" },
    { id: "PanteleykoA24", name: "Пантелейко Артем" },
    { id: "SavinaE32", name: "Савина Елизавета" },
    { id: "IvanovI19", name: "Иванов Иван" }
]
};
